/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/CbusConnection/GetComPorts": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": string[];
            "application/json": string[];
            "text/json": string[];
          };
        };
      };
    };
  };
  "/CbusConnection/Connect": {
    post: {
      responses: {
        /** Success */
        200: {
          content: {
            "text/plain": boolean;
            "application/json": boolean;
            "text/json": boolean;
          };
        };
      };
      requestBody: {
        content: {
          "application/json": components["schemas"]["ConnectionOptions"];
          "text/json": components["schemas"]["ConnectionOptions"];
          "application/*+json": components["schemas"]["ConnectionOptions"];
        };
      };
    };
  };
}

export interface components {
  schemas: {
    ConnectionOptions: {
      connectionType?: components["schemas"]["ConnectionTypes"];
      serialPort?: components["schemas"]["SerialPortTransportSettings"];
      tcp?: components["schemas"]["TcpTransportSettings"];
    };
    /**
     * Format: int32
     * @example 0: SerialPort, 1: Tcp
     * @enum {integer}
     */
    ConnectionTypes: 0 | 1;
    SerialPortTransportSettings: {
      portName?: string | null;
      /** Format: int32 */
      baudRate?: number | null;
      /** Format: int32 */
      dataBits?: number | null;
      stopBits?: string | null;
      parity?: string | null;
    };
    TcpTransportSettings: {
      /** Format: int32 */
      port?: number;
      host?: string | null;
    };
  };
}

export interface operations {}

export interface external {}
